# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 13:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_host_host_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_address',
            field=models.TextField(default=datetime.datetime(2016, 6, 8, 13, 45, 35, 259780, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='host_type',
            field=models.TextField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
