# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20160608_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_data_create',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
