# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_host_host_data_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_status',
            field=models.TextField(max_length=20),
        ),
    ]
