# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_hostdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostdetails',
            name='detail_content',
            field=models.TextField(max_length=255),
        ),
    ]
