# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20160609_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostdetails',
            name='detail_data_audit',
        ),
    ]
