# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_remove_hostdetails_detail_data_audit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostDetails',
        ),
    ]
