# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_delete_hostdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_content', models.TextField(max_length=255)),
                ('detail_data_audit', models.DateField(auto_now=True)),
            ],
        ),
    ]
