# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_hostdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostdetails',
            old_name='detail_data_audit',
            new_name='detail_date_audit',
        ),
        migrations.AlterField(
            model_name='hostdetails',
            name='detail_content',
            field=models.TextField(max_length=65000),
        ),
    ]
