# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20160609_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostdetails',
            name='detail_host_id',
            field=models.TextField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
