# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_vulnerability_detail_host_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vulnerability',
            old_name='detail_host_id',
            new_name='host_id',
        ),
    ]
