# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_vulnerability_cve_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVEdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve', models.TextField(max_length=65000)),
                ('description', models.TextField(max_length=65000)),
                ('score', models.TextField(max_length=65000)),
            ],
        ),
    ]
