# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_cvedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostdetails',
            name='detail_content',
        ),
        migrations.AlterField(
            model_name='cvedetails',
            name='score',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
