# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_auto_20160623_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvedetails',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
